title = "JdM’s Site"
description = "I create digital solutions optimized for computers, comfortable for users and innovative for the world."

author = "Julien de Montmollin"

generate_sitemap = true
generate_robots_txt = true

generate_feeds = true
feed_filenames = ["rss.xml"]

# The URL the site will be built for
base_url = "https://futureofthe.tech"


theme = "linkita"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
comment = true
header_menu_name = "menu"

[extra.menus]
menu = [
    { url = "$BASE_URL/about/", name = "About" },

    { url = "$BASE_URL/projects/", name = "Projects" },
    { url = "$BASE_URL/blog/", name = "Blog" },
    { url = "$BASE_URL/bookmarks/", name = "Bookmarks" },

    { url = "$BASE_URL/donate/", name = "Donate" },


#   { url = "$BASE_URL/categories/", name = "Categories" },
#   { url = "$BASE_URL/tags/", name = "Tags" },
]



[extra.profiles.judemont]

# The URL of avatar.
# e.g. "icons/github.svg"
avatar_url = "images/me.png"

# A description of what is in the avatar.
avatar_alt = "me"

# Invert avatar color in dark mode.
# Default value: false
avatar_invert = false

# Profile name.
# Default value: the username
name = "JdM"

# Profile bio.
# Supports Markdown.
bio = """ 
I create digital solutions optimized for computers, comfortable for users and innovative for the world.

Hi, I’m JdM. I’m passionate about development. As a computer science student, I use my skills in this field to innovate and create while contributing to a more free, open, and secure internet.

Far beyond the digital realm, I want to bring my motivation to the real world by sharing my ideas and my determination to improve the world.

I would like to build a world of innovation. A more free world. A world where online privacy is not violated. A more prosperous world. A more sustainable world. But also a world of peace.

A world that would benefit all of humanity.

I believe that many people are aware of these issues. My goal is to imagine solutions.

![My setup](images/setup.jpg)
"""

# Social icons.
# "name" should be the file name of "static/icons/*.svg" or
# the icon name of https://simpleicons.org/
# "url" supports "$BASE_URL".
# Other variables: "urls", "title", "titles".
social = [
    { name = "github", url = "https://github.com/judemont" },
    { name = "signal", url = "https://signal.me/#eu/F5CqLbRjbB-Sl8nL-6HtD3Sg7zbbUq4TcQWOp56-ygzyYVoVm0NIxpZAgwTAka4u" },
    { name = "telegram", url = "https://t.me/judemont" },
    { name = "matrix", url = "https://matrix.to/#/@judemont:matrix.org" },
    { name = "email", url = "mailto:julien@rmbi.ch" },
    { name = "rss", url = "$BASE_URL/rss.xml" },
]