<?php

$data = file_get_contents('blog/articles.json');
$articles = json_decode($data, true);
$articles = array_reverse($articles);
?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JdM's Site</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <header>
        <h1>Welcome to JdM's Site</h1>
        <b>I devote my time to Imagining and Creating the Future of the Humanity 🌐.</b>
    </header>
    <br><br>
    <h2>Table of content</h2>
    <ul>
        <li><a href="#social">Social</a></li>
        <li><a href="#about">About Me</a></li>
        <li><a href="#projects">My Projects</a></li>
        <li><a href="#blog">Articles by me</a></li>
        <li><a href="#support">Support my work</a></li>
    </ul>
    <br>
    <h2 id="social">Social :</h2>
    <ul>
        <li><a href="https://github.com/judemont">GitHub</a></li>
        <li><a href="https://www.linkedin.com/in/julien-de-montmollin/">Linkedin</a></li>
        <li><a href="https://signal.me/#eu/F5CqLbRjbB-Sl8nL-6HtD3Sg7zbbUq4TcQWOp56-ygzyYVoVm0NIxpZAgwTAka4u">Signal</a>
        </li>
        <li><a href="https://t.me/judemont">Telegram</a></li>
        <li><a href="mailto:julien@rmbi.ch">eMail</a></li>
    </ul>
    <br>
    <h2 id="about">About Me :</h2>
    <p class="about-text">
        <i>I devote my time to Imagining and Creating the Future of the Humanity 🌐. A future we all
            want.</i><br><br>

        Hi i'm JdM. I'm passionate about development. <br>As a computer science student I use my skills in this
        field to
        innovate and create while contributing to a more free, open and secure internet.
        <br><br>
        Far beyond the digital realm, I want to bring my motivation to the real world by sharing my ideas and my
        determination to improve the world.
        <br><br>
        I would like to build a world of innovation. A more free world. A world where online privacy is not
        violated. A more prosperous world. A more sustainable world. But also a world of peace.
        <br><br>
        <b>A world that would benefit all of humanity.</b>
        <br><br>
        I believe that many people are aware of these issues. My goal is to imagine <b>solutions</b>.
    </p>
    <br>
    <h2 id="projects">My Projects</h2>
    <ul>
        <li>
            <a href="https://github.com/judemont/QuizFlow" target="_blank" rel="noreferrer">QuizFlow</a>
            - Create, and study word lists with interactive flashcards and modes - Free & open source Quizlet
            alternative
        </li>
        <li>
            <a href="https://github.com/judemont/reciper" target="_blank" rel="noreferrer">Reciper</a>
            - Your Ultimate Kitchen Companion! Manage your recipes with ease using Reciper
        </li>
        <li>
            <a href="https://github.com/judemont/cryptotracker" target="_blank" rel="noreferrer">CryptoTracker</a>
            - Track cryptocurrency prices in real-time with CryptoTracker
        </li>
        <li>
            <a href="https://github.com/judemont/netexplorer" target="_blank" rel="noreferrer">NetExplorer</a>
            - Web analysis tool
        </li>
        <li>
            <a href="https://t.me/united_nations_news" target="_blank" rel="noreferrer">United Nations News</a>
            - United Nations News on Telegram from news.un.org
        </li>
        <li>
            <a href="https://t.me/down_alertbot" target="_blank" rel="noreferrer">Down Alert</a>
            - Telegram bot that checks if your websites are down and then alerts you
        </li>
        <li>
            <a href="https://futureofthe.world" target="_blank" rel="noreferrer">FutureOfThe.World</a>
            - Future Of The World
        </li>
        <li>
            <a href="https://github.com/judemont/Video-to-CSS" target="_blank" rel="noreferrer">Video to CSS</a>
            - Convert your videos into CSS animation
        </li>
        <li>
            <a href="https://github.com/judemont/typing-bot" target="_blank" rel="noreferrer">Typing Bot</a>
            - Automatic typing browser extension for cheating on typing tests
        </li>
        <li>
            <a href="https://github.com/judemont/chatgpt-html-web-view" target="_blank" rel="noreferrer">ChatGPT HTML
                Web View</a>
            - Browser extension to quickly preview Website generated by ChatGPT
        </li>
    </ul>
    <br>
    <h2 id="blog">Articles by <i>Me</i></h2>
    <ul>
        <?php
            $i = 0;
            foreach ($articles as $article) {
                echo "
                <li>
                    <a href=\"blog/read.php?i=$i\"><b>{$article['title']}</b></a> <br>
                    <i>{$article['date']}</i> <br>
                    <b>{$article['readTime']}</b>
                </li>";
                $i++;
            }
        ?>
    </ul>
    <br>
    <h2 id="support">Support My Work</h2>
    <div class="support">
        <h4>Bitcoin :</h4>
        <p>bc1qhmkpytvs42w27pgqrk7kljy5hvarzx6tll8ar6</p>
        <h4>Monero :</h4>
        <p>49pyL3WPqfqfaLweCYFYbsWQi2bvKqmAHixewxnDBi32DKiPQz9kgJ5g6VnvENLqWbD5iGasQQvG7GVVg6B3HYu5Gqx4JSn</p>
    </div>
    <br><br>
    <footer>
        <p><img src="nocopyright.svg" alt="No copyright" width="25"> No rights reserved.</p>
    </footer>
</body>

</html>