[[project]]
name = "QuizFlow"
desc = "Create and study word lists with interactive flashcards and modes - Free & open source Quizlet alternative."
tags = ["flutter", "android", "app"]
links = [
    { name = "source", url = "https://github.com/judemont/QuizFlow" },
]

[[project]]
name = "Reciper"
desc = "Your Ultimate Kitchen Companion! Manage your recipes with ease using Reciper."
tags = ["flutter", "android", "app"]
links = [
    { name = "source", url = "https://github.com/judemont/reciper" },
]

[[project]]
name = "CryptoTracker"
desc = "Track cryptocurrency prices in real-time with CryptoTracker."
tags = ["flutter", "android", "app"]
links = [
    { name = "source", url = "https://github.com/judemont/cryptotracker" },
]

[[project]]
name = "CryptoFlow"
desc = "Track cryptocurrency prices in style and privacy with CryptoFlow."
tags = ["flutter","software", ]
links = [
    { name = "source", url = "https://github.com/judemont/CryptoFlow" },
]

[[project]]
name = "Tcoin"
desc = "Get real-time data and charts for any cryptocurrency without leaving your terminal."
tags = ["go","software", "cli"]
links = [
    { name = "source", url = "https://github.com/judemont/tcoin" },
]

[[project]]
name = "FutureOfThe.World"
desc = "Can a website save the world? No. But you can."
tags = ["website"]
links = [
    { name = "homepage", url = "https://futureofthe.world" },
]

[[project]]
name = "FutureOfThe.Tech"
desc = "My presentation site."
tags = ["website"]
links = [
    { name = "homepage", url = "https://futureofthe.tech" },
]

[[project]]
name = "NetExplorer"
desc = "Web analysis tool."
tags = ["python","tool"]
links = [
    { name = "source", url = "https://github.com/judemont/netexplorer" },
]

[[project]]
name = "VisuHash"
desc = "Creates a unique visual representation of a text, or file."
tags = ["rust", "software", "cli"]
links = [
    { name = "source", url = "https://github.com/judemont/visuhash" },
]

[[project]]
name = "Video to CSS"
desc = "Convert your videos into CSS animation."
tags = ["python","tool"]
links = [
    { name = "source", url = "https://github.com/judemont/Video-to-CSS" },
]

[[project]]
name = "Down Alert"
desc = "Telegram bot that checks if your websites are down and then alerts you."
tags = ["python","telegram bot"]
links = [
    { name = "homepage", url = "https://t.me/down_alertbot" },
]

[[project]]
name = "Typing Bot"
desc = "Automatic typing browser extension for cheating on typing tests."
tags = ["browser extension"]
links = [
    { name = "source", url = "https://github.com/judemont/typing-bot" },
]

[[project]]
name = "ChatGPT HTML Web View"
desc = "Browser extension to quickly preview websites generated by ChatGPT."
tags = ["browser extension"]
links = [
    { name = "source", url = "https://github.com/judemont/chatgpt-html-web-view" },
]


